//! Per-session hook artifacts injected into spawned agent CLIs. Written
//! under `run/terminal-sessions/<session_id>/` — never into the user's
//! global agent config (`~/.claude`, `~/.pi`).

use std::path::PathBuf;

use anyhow::{Context, Result};

/// The hook command pings the local hook server. Env vars resolve inside
/// the hook's `sh -c` because hooks inherit the agent process env, which
/// inherits the PTY env Helmor sets at spawn. `|| true` keeps a dead
/// Helmor (or blocked curl) from failing the agent's hook pipeline.
fn ping_command(event: &str) -> String {
    format!(
        "curl -fsS -m 3 -X POST \"http://127.0.0.1:${{HELMOR_HOOK_PORT}}/terminal-hooks/${{HELMOR_TERMINAL_SESSION_ID}}?event={event}\" -H \"x-helmor-token: ${{HELMOR_HOOK_TOKEN}}\" -H \"content-type: application/json\" --data-binary @- >/dev/null 2>&1 || true"
    )
}

pub fn artifacts_dir(session_id: &str) -> Result<PathBuf> {
    let dir = crate::data_dir::run_dir()?
        .join("terminal-sessions")
        .join(session_id);
    std::fs::create_dir_all(&dir).context("Failed to create terminal session artifacts dir")?;
    Ok(dir)
}

pub fn remove_artifacts(session_id: &str) {
    if let Ok(run_dir) = crate::data_dir::run_dir() {
        let dir = run_dir.join("terminal-sessions").join(session_id);
        let _ = std::fs::remove_dir_all(dir);
    }
}

/// Sweep all per-session artifact dirs (app start — stale by definition).
pub fn remove_all_artifacts() {
    if let Ok(run_dir) = crate::data_dir::run_dir() {
        let _ = std::fs::remove_dir_all(run_dir.join("terminal-sessions"));
    }
}

/// Generated settings JSON for `claude --settings <path>`. Merges
/// additively with the user's global settings; only adds hooks.
pub fn claude_settings_json() -> serde_json::Value {
    let single = |event: &str| {
        serde_json::json!([{
            "hooks": [{ "type": "command", "command": ping_command(event) }]
        }])
    };
    serde_json::json!({
        "hooks": {
            "SessionStart": single("SessionStart"),
            "UserPromptSubmit": single("UserPromptSubmit"),
            "PreToolUse": [{
                "matcher": "*",
                "hooks": [{ "type": "command", "command": ping_command("PreToolUse") }]
            }],
            "Stop": single("Stop"),
            "Notification": single("Notification"),
        }
    })
}

pub fn write_claude_settings(session_id: &str) -> Result<PathBuf> {
    let path = artifacts_dir(session_id)?.join("claude-settings.json");
    let json = serde_json::to_string_pretty(&claude_settings_json())
        .context("Failed to serialize claude hook settings")?;
    std::fs::write(&path, json).context("Failed to write claude hook settings")?;
    Ok(path)
}

/// Generated pi extension for `pi --extension <path>`. Subscribes to agent
/// lifecycle events and pings the hook server. Fire-and-forget fetch —
/// failures never disturb the agent.
pub fn pi_extension_source() -> String {
    r#"// Generated by Helmor — per-session status reporting. Safe to ignore.
export default function helmorStatus(pi: any) {
	const post = (event: string) => {
		const port = process.env.HELMOR_HOOK_PORT;
		const session = process.env.HELMOR_TERMINAL_SESSION_ID;
		if (!port || !session) return;
		fetch(`http://127.0.0.1:${port}/terminal-hooks/${session}?event=${event}`, {
			method: "POST",
			headers: {
				"x-helmor-token": process.env.HELMOR_HOOK_TOKEN ?? "",
				"content-type": "application/json",
			},
			body: "{}",
		}).catch(() => {});
	};
	pi.on("session_start", () => post("session_start"));
	pi.on("agent_start", () => post("agent_start"));
	pi.on("agent_end", () => post("agent_end"));
	pi.on("turn_start", () => post("turn_start"));
}
"#
    .to_string()
}

pub fn write_pi_extension(session_id: &str) -> Result<PathBuf> {
    let path = artifacts_dir(session_id)?.join("helmor-status.ts");
    std::fs::write(&path, pi_extension_source()).context("Failed to write pi hook extension")?;
    Ok(path)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn claude_settings_cover_all_five_hook_events() {
        let json = claude_settings_json();
        let hooks = json.get("hooks").and_then(|h| h.as_object()).unwrap();
        for event in [
            "SessionStart",
            "UserPromptSubmit",
            "PreToolUse",
            "Stop",
            "Notification",
        ] {
            let entries = hooks.get(event).and_then(|e| e.as_array()).unwrap();
            let command = entries[0]["hooks"][0]["command"].as_str().unwrap();
            assert!(
                command.contains("${HELMOR_HOOK_PORT}"),
                "{event}: {command}"
            );
            assert!(
                command.contains("${HELMOR_TERMINAL_SESSION_ID}"),
                "{event}: {command}"
            );
            assert!(command.contains(&format!("event={event}")), "{command}");
            assert!(command.ends_with("|| true"), "{command}");
        }
        // PreToolUse must carry the match-everything matcher.
        assert_eq!(hooks["PreToolUse"][0]["matcher"], "*");
    }

    #[test]
    fn pi_extension_subscribes_to_lifecycle_events() {
        let source = pi_extension_source();
        for event in ["session_start", "agent_start", "agent_end", "turn_start"] {
            assert!(source.contains(&format!("pi.on(\"{event}\"")), "{event}");
        }
        assert!(source.contains("HELMOR_HOOK_TOKEN"));
    }
}
